Add JavaScript ES6 to update folder
tastejs/todomvc pull request #2207
Opened 2023-09-22 15:29 UTC by flashdesignory

This version has been lifted from Speedometer and follows the WebKit styles guide.

For more context regarding this update, please view https://github.com/tastejs/todomvc/issues/2199.

@kara

2023-10-09 18:34 UTC, manish-mehra commented
That's exactly what I was looking for. With es6 classes, the code is more readable and I can comprehend it as a newbie.  Thanks @flashdesignory🙇🏻‍♂️. Waiting for the pull request to be merged.

2023-10-22 22:48 UTC, FadySamirSadek requested changes
LGTM, other than the 2 typos in the README.

2023-10-22 22:48 UTC, FadySamirSadek commented on updates/javascript-es6/README.md
> +## Built steps
*build Steps

2023-10-22 22:48 UTC, FadySamirSadek commented on updates/javascript-es6/README.md
> +## Implementation details
Implementation Details

2023-10-30 23:19 UTC, FadySamirSadek approved these changes

2023-10-30 23:31 UTC, merged