Update ember
tastejs/todomvc pull request #2261
Opened 2024-10-09 01:17 UTC by NullVoxPopuli

Aiming to resolve: https://github.com/tastejs/todomvc/issues/2255

2024-10-10 15:59 UTC, flashdesignory commented
@NullVoxPopuli - you're right, the site needs node 8 to run with gulp.
I believe it's `npm run gulp serve` from root.

(@FadySamirSadek - in case I am forgetting something here)

2024-10-10 16:11 UTC, NullVoxPopuli commented
I can't get it to run:
```bash
❯ npm run gulp serve

> todomvc@0.1.2 gulp
> gulp serve

fs.js:43
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:43:5
    at req_ (<repo>/node_modules/natives/index.js:137:5)
    at Object.req [as require] (<repo>/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (<repo>/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)

```

2024-10-10 16:21 UTC, flashdesignory commented
@NullVoxPopuli  - are you using node 8.17.0?
You might have to run install again after switching, but the command is pretty much what I'm using.

2024-10-10 17:01 UTC, NullVoxPopuli commented
install never finishes

2024-10-28 17:25 UTC, flashdesignory requested changes
in your learn.json file, please update "emberjs" (on line 403) to just "ember". 
In that way it matches your index.html file (<!DOCTYPE html><html lang="en" data-framework="ember">...).

I was able to pull your branch, install and run it. Not sure why it's not working for you locally... the old node version might be a bit wonky to work with 🤷 .

2024-10-28 17:25 UTC, flashdesignory commented on learn.json
> +				"url": "https://hachyderm.io/@emberjs",
nit: trailing comma

2024-10-28 17:46 UTC, NullVoxPopuli commented
thanks, updated!

2024-10-28 17:46 UTC, NullVoxPopuli commented
>  Not sure why it's not working for you locally

I couldn't find what combination of npm/node to use -- I suspect that if I have the right combo of versions, I could run things

2024-10-28 17:53 UTC, merged